In [ ]:
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats import contin


In [2]:
sb_data = pd.read_csv(r"superbowl.csv")
sb_data.tail()

Super Bowl Coin Toss Outcome Coin Toss Winner Game Winner
50          51             Tails        Home Team   Away Team
51          52             Heads        Home Team   Away Team
52          53             Tails        Home Team   Away Team
53          54             Tails        Away Team   Home Team
54          55             Heads        Away Team   Home Team

In [4]:
sb_data["Coin Toss Winner"].value_counts()

Coin Toss Winner
Away Team    30
Home Team    25
Name: count, dtype: int64

In [5]:
sb_data["Game Winner"].value_counts()

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [7]:
coin_toss_counts = sb_data["Coin Toss Outcome"].value_counts()


In [8]:
fair_coin_expected =[sum(coin_toss_counts)/2,sum(coin_toss_counts)/2]
fair_coin_expected

[27.5, 27.5]

In [9]:
fair_coin_observed = coin_toss_counts.values
fair_coin_observed

array([29, 26])

In [10]:
fair_coin_result=stats.chisquare(fair_coin_observed,fair_coin_expected)
fair_coin_result

Power_divergenceResult(statistic=np.float64(0.16363636363636364), pvalue=np.float64(0.6858304344516056))

In [13]:
fair_gamewinner_counts= sb_data["Game Winner"].value_counts()
fair_gamewinner_counts

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [16]:
observed = fair_gamewinner_counts.values
observed

array([31, 24])

In [18]:
expected = [sum(fair_gamewinner_counts)/2, sum(fair_gamewinner_counts)/2]
expected

[27.5, 27.5]

In [19]:
results= stats.chisquare(observed, expected)
results

Power_divergenceResult(statistic=np.float64(0.8909090909090909), pvalue=np.float64(0.34523107177184))

In [20]:
nfl_games= pd.read_csv(r"nfl_games.csv")
nfl_games.tail()

date  season  neutral  playoff team1 team2         elo1  \
16805  2021-01-17    2020        0        1    KC   CLE  1712.652090   
16806  2021-01-17    2020        0        1    NO    TB  1704.051294   
16807  2021-01-24    2020        0        1    GB    TB  1715.623187   
16808  2021-01-24    2020        0        1    KC   BUF  1719.618921   
16809  2021-02-07    2020        1        1    TB    KC  1703.303296   

              elo2  elo_prob1  score1  score2  result1  
16805  1552.012725   0.785647      22      17      1.0  
16806  1645.074008   0.671212      20      30      0.0  
16807  1679.186255   0.641968      26      31      0.0  
16808  1719.974149   0.591972      38      24      1.0  
16809  1741.087279   0.445838      31       9      1.0

In [21]:
# Data from FiveThirtyEight
nfl_games = pd.read_csv("nfl_games.csv")
# Narrow to relevant rows
nfl_games = nfl_games[(nfl_games["neutral"] == 0) & (nfl_games["playoff"] == 0) & (nfl_games["season"] >= 1966 )]
# Engineer a new feature
nfl_games.loc[nfl_games["result1"] == 0, "Game Winner"] = "Away Team"
nfl_games.loc[nfl_games["result1"] == 1, "Game Winner"] = "Home Team"

game_winner_counts_nfl = nfl_games["Game Winner"].value_counts().sort_index()
game_winner_counts_nfl

Game Winner
Away Team    5265
Home Team    7066
Name: count, dtype: int64

In [22]:
nfl_observed = game_winner_counts_nfl.values
nfl_observed


array([5265, 7066])

In [25]:
nfl_expected = [sum(game_winner_counts_nfl) / 2,sum(game_winner_counts_nfl) / 2]
nfl_expected


[6165.5, 6165.5]

In [26]:
nfl_chi_square = stats.chisquare(nfl_observed, nfl_expected)
nfl_chi_square

Power_divergenceResult(statistic=np.float64(263.0444408401589), pvalue=np.float64(3.7231908240550128e-59))

In [29]:
independence_table = pd.crosstab(sb_data["Coin Toss Winner"], sb_data["Game Winner"])
independence_table

Game Winner       Away Team  Home Team
Coin Toss Winner                      
Away Team                15         15
Home Team                16          9

In [41]:
chi2,p,dof,exf=stats.chi2_contingency(independence_table)
print(chi2,p,dof,exf)

0.5920138888888885 0.44164141533080714 1 [[16.90909091 13.09090909]
 [14.09090909 10.90909091]]
