#### Data analysis with python

File input/output

with statement - used in file handling to avoid forgetting to close the file

In [2]:
with open("sample.txt", "w") as file:
    file.write("Hello, World!")

In [1]:
with open("sample.txt", "r") as file:
    content= file.read()
    print(content)


Hello, World!


In [4]:
with open("Excel_jumia 1.csv","r") as file:
    content2= file.read()
    print(content2)


Product,Current price,old price,Discount,Review,Ratingd
115  Piece Set Of Multifunctional Precision Screwdrivers,KSh 950,"KSh 1,525",38%,-2,4.5 out of 5
Metal Decorative Hooks Key Hangers Entryway Wall Hooks Towel Hooks - Home,KSh 527,KSh 999,47%,-14,4.1 out of 5
Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%,-24,4.6 out of 5
Weighing Scale Digital Bathroom Body Fat Scale USB-Black,"KSh 1,580","KSh 2,499",37%,-7,4.7 out of 5
Portable Home Small Air Humidifier 3-Speed Fan - Green,"KSh 1,740","KSh 2,356",26%,-5,4.8 out of 5
"220V 60W Electric Soldering Iron Kits With Tools, Tips, And Multimeter","KSh 2,999","KSh 3,290",9%,-15,4 out of 5
137 Pieces Cake Decorating Tool Set Baking Supplies,"KSh 2,319","KSh 3,032",24%,-55,4.6 out of 5
Desk Foldable Fan Adjustable Fan Strong Wind 3 Gear Usb,KSh 988,"KSh 1,580",37%,-2,4 out of 5
LASA FOLDING TABLE SERVING STAND,"KSh 1,274","KSh 2,800",55%,-5,4.8 out of 5
13 In 1 Home Repair Tools Box Kit Set,"KSh 1,600","KSh 2,92

In [6]:
import pandas as pd
df = pd.read_csv(r"Excel_jumia 1.csv")
df.head()



Product Current price  old price  \
0  115  Piece Set Of Multifunctional Precision Sc...       KSh 950  KSh 1,525   
1  Metal Decorative Hooks Key Hangers Entryway Wa...       KSh 527    KSh 999   
2   Portable Mini Cordless Car Vacuum Cleaner - Blue     KSh 2,199  KSh 2,923   
3  Weighing Scale Digital Bathroom Body Fat Scale...     KSh 1,580  KSh 2,499   
4  Portable Home Small Air Humidifier 3-Speed Fan...     KSh 1,740  KSh 2,356   

  Discount  Review       Ratingd  
0      38%    -2.0  4.5 out of 5  
1      47%   -14.0  4.1 out of 5  
2      25%   -24.0  4.6 out of 5  
3      37%    -7.0  4.7 out of 5  
4      26%    -5.0  4.8 out of 5

In [8]:
df.to_csv("sample.csv", index=False)

Pandas is a powerful library for data analysis and is used to manipulate data sets it provides 2 data structures:
1. series - which is like column
2. data frame- ia a table 

In [10]:
#loading data set
df= pd.read_csv(r"Excel_jumia 1.csv")
df.head(10)


Product Current price  old price  \
0  115  Piece Set Of Multifunctional Precision Sc...       KSh 950  KSh 1,525   
1  Metal Decorative Hooks Key Hangers Entryway Wa...       KSh 527    KSh 999   
2   Portable Mini Cordless Car Vacuum Cleaner - Blue     KSh 2,199  KSh 2,923   
3  Weighing Scale Digital Bathroom Body Fat Scale...     KSh 1,580  KSh 2,499   
4  Portable Home Small Air Humidifier 3-Speed Fan...     KSh 1,740  KSh 2,356   
5  220V 60W Electric Soldering Iron Kits With Too...     KSh 2,999  KSh 3,290   
6  137 Pieces Cake Decorating Tool Set Baking Sup...     KSh 2,319  KSh 3,032   
7  Desk Foldable Fan Adjustable Fan Strong Wind 3...       KSh 988  KSh 1,580   
8                   LASA FOLDING TABLE SERVING STAND     KSh 1,274  KSh 2,800   
9              13 In 1 Home Repair Tools Box Kit Set     KSh 1,600  KSh 2,929   

  Discount  Review       Ratingd  
0      38%    -2.0  4.5 out of 5  
1      47%   -14.0  4.1 out of 5  
2      25%   -24.0  4.6 out of 5  
3      37%    -7.0  4.7 out of 5  
4      26%    -5.0  4.8 out of 5  
5       9%   -15.0    4 out of 5  
6      24%   -55.0  4.6 out of 5  
7      37%    -2.0    4 out of 5  
8      55%    -5.0  4.8 out of 5  
9      45%    -5.0  3.8 out of 5

In [11]:
#view information about the data set
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Product        115 non-null    object 
 1   Current price  115 non-null    object 
 2   old price      115 non-null    object 
 3   Discount       115 non-null    object 
 4   Review         57 non-null     float64
 5   Ratingd        57 non-null     object 
dtypes: float64(1), object(5)
memory usage: 5.5+ KB


In [12]:
#checking for missing values
df.isnull().sum()

Product           0
Current price     0
old price         0
Discount          0
Review           58
Ratingd          58
dtype: int64

In [20]:
#fillna method- is used to fill missing values in columns
#drop the 2 columns ratings and reviews
df = df.drop(columns = ["Ratingd", "Review"], axis=1)
df.head()

Product Current price  old price  \
0  115  Piece Set Of Multifunctional Precision Sc...       KSh 950  KSh 1,525   
1  Metal Decorative Hooks Key Hangers Entryway Wa...       KSh 527    KSh 999   
2   Portable Mini Cordless Car Vacuum Cleaner - Blue     KSh 2,199  KSh 2,923   
3  Weighing Scale Digital Bathroom Body Fat Scale...     KSh 1,580  KSh 2,499   
4  Portable Home Small Air Humidifier 3-Speed Fan...     KSh 1,740  KSh 2,356   

  Discount  
0      38%  
1      47%  
2      25%  
3      37%  
4      26%

In [21]:
titanic = pd.read_csv("tested.csv")
titanic.head(10)

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   
5          897         0       3   
6          898         1       3   
7          899         0       2   
8          900         1       3   
9          901         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
5                    Svensson, Mr. Johan Cervin    male  14.0      0      0   
6                          Connolly, Miss. Kate  female  30.0      0      0   
7                  Caldwell, Mr. Albert Francis    male  26.0      1      1   
8     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0      0   
9                       Davies, Mr. John Samuel    male  21.0      2      0   

      Ticket     Fare Cabin Embarked  
0     330911   7.8292   NaN        Q  
1     363272   7.0000   NaN        S  
2     240276   9.6875   NaN        Q  
3     315154   8.6625   NaN        S  
4    3101298  12.2875   NaN        S  
5       7538   9.2250   NaN        S  
6     330972   7.6292   NaN        Q  
7     248738  29.0000   NaN        S  
8       2657   7.2292   NaN        C  
9  A/4 48871  24.1500   NaN        S

In [22]:
titanic.groupby("Pclass")["Fare"].sum()

Pclass
1    10087.9918
2     2064.7957
3     2703.7501
Name: Fare, dtype: float64

In [23]:
class Employee:
    def __init__(self,salary):
        self.salary = salary
        


In [25]:
class Manager(Employee):
    def department(self, dept_name):
        self.dept_name= dept_name
        return f"I work in the {dept_name} department and my salary is {self.salary}"

In [28]:
worth =Manager(5000)
print(worth.department("HR"))

I work in the HR department and my salary is 5000


#### Numpy
-it's numerical python
-its a fast efficient library for computing 
-provides a high perfomance array object and tools to work with 


In [29]:
numbers= [1,2,3,4,5,6,7,8,9,10 ]
nums= [10,9,8,7,6,5,4,3,2,1]
add1=numbers + nums
print(add1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [31]:
import numpy as np


In [32]:
numbers_array=np.array(numbers)
numbers_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
nums_array=np.array(nums)
print(nums_array)

[10  9  8  7  6  5  4  3  2  1]


In [34]:
add2=numbers_array+nums_array
print(add2)

[11 11 11 11 11 11 11 11 11 11]


In [35]:
numbers_array.mean()

np.float64(5.5)

In [37]:
numbers_array.sum()

np.int64(55)

In [38]:
numbers_array.std()

np.float64(2.8722813232690143)

In [39]:
numbers_array.var()

np.float64(8.25)

In [40]:
titanic["Age"].mean()

np.float64(30.272590361445783)